### ISSUE TITLE
feat: ignore files based on pattern

### ISSUE THREAD

**Issue by massivebird** [massivebird/arcsearch#20]
There's a file called `games.bin` in my PS2 directory that was automatically generated by something (maybe OPL). Since it'll be regenerated if I rename or move it, I want to ignore the file altogether.

Maybe in `config.yaml` I can add some attribute that ignores files based on a regex pattern.

```yaml
# config.yaml
ignore: "^!.*" # << optional attribute applied globally

systems:
  ps2:
    display_name: "PS2"
    color: [102,102,102]
    path: "DVD"
    games_are_directories: false
    ignore: "games.bin" # << optional attribute
  ps1:
    display_name: "PS1"
    color: [178,178,178]
    path: "ps1"
    games_are_directories: true
```
