### ISSUE TITLE
Only query specified systems

### ISSUE THREAD

**Issue by massivebird** [massivebird/arcsearch#7]
Queries could be constrained to only query specific systems, specified by label.

For example:

```yaml
# config.yaml
systems:
  myds: # system "label"
    display_name: "DS"
    color: [135,215,255]
    path: "ds"
    games_are_directories: false
  # more systems...
```

If I only wanted to search through my DS games, I could hypothetically do something like this:

```bash
arcsearch --systems="myds" "mario"
```
